### ISSUE TITLE
issues with straingr view: --vcf and --verbose-vcf arguments produced no or unexpected output

### ISSUE THREAD

**Issue by biolene** [broadinstitute/StrainGE#10]
Thanks for providing this interesting new tool, it has mostly worked seamlessly, and it is producing promising results for my samples.

However, when I want to generate vcf files I encounter some problems.

I tried to generate vcf files for my sample with `straingr view`.
With the default level (`--verbose-vcf 0`) I get a vcf file, but the output does not appear to be correct: it lists a GT value of 0 for all entries, regardless of whether the call at that position is the reference allele or not. Is this the intended output?

When I set `--verbose-vcf 2`, I get an error:

> Traceback (most recent call last):
  File "/home/jodaes/strainge/bin/straingr", line 8, in <module>
    sys.exit(straingr_cli())
  File "/home/jodaes/strainge/lib/python3.8/site-packages/strainge/cli/main.py", line 110, in __call__
    self.run(args)
  File "/home/jodaes/strainge/lib/python3.8/site-packages/strainge/cli/registry.py", line 83, in run
    rc = subcommand_func(**args_dict)
  File "/home/jodaes/strainge/lib/python3.8/site-packages/strainge/cli/straingr.py", line 588, in __call__
    write_vcf(call_data, vcf, verbose_vcf)
  File "/home/jodaes/strainge/lib/python3.8/site-packages/strainge/io/variants.py", line 477, in write_vcf
    for record in record_iter:
  File "/home/jodaes/strainge/lib/python3.8/site-packages/strainge/io/variants.py", line 406, in vcf_records_for_scaffold
    weighted_base_freqs = [v / sum_quals for v in allele_quals]
  File "/home/jodaes/strainge/lib/python3.8/site-packages/strainge/io/variants.py", line 406, in <listcomp>
    weighted_base_freqs = [v / sum_quals for v in allele_quals]
ZeroDivisionError: division by zero

It is not entirely clear to me which positions are supposed to be included with this setting. the documentation states that 'If set to 2, it will include an entry for every position in the reference, even if no other base than the reference is observed.' So does this mean that an entry will be produced for every position in the reference (including the 'repetitive' regions), or for every position for which there was a call made?

Thank you for taking a look at this!

**Comment by lrvdijk** [comment]
This seems like a bug indeed, I'll check it out!

**Comment by lrvdijk** [comment]
Alright, I've looked into it, and unfortunately I had to remove verboseness level 2. Pysam's VCF writer doesn't allow us to write VCF entries without an ALT record.

Regarding the genotype column, please ignore it, we don't use it and specify an empty GT indeed. Inspect the ALT column to see which alleles are there, and inspect the INFO fields for more metrics (Depth of coverage per allele, allele fraction, whether it's a strongly called allele or not, etc.)

If you're looking for variants within repetitive regions, you'll have to run `straingr call` with `-M 0` (minimum mapping quality 0).

**Comment by biolene** [comment]
OK, thanks for the feedback!
