### ISSUE TITLE
ncbi-genome-download `ERROR: No entry for file ending in '_rm.out.gz'`

### ISSUE THREAD

**Issue by drelo** [broadinstitute/StrainGE#2]
Dear developers, since I have no previous experience with StrainGE I would want to check If I missed something here. After a few failed attempts I run this with debug and I am attaching the file now.

`ncbi-genome-download bacteria -l complete -g Salmonella -H -F all -o ref_genomes -d 2> ERROR .txt `

The line generates folders but no genome is downloaded

```
ref_genomes
├── human_readable
│   └── refseq
│       └── bacteria
│           └── Salmonella
│               └── enterica
│                   ├── 1326_28
│                   ├── CFSAN003307
│                   ├── CVM44454
│                   ├── FSIS1502169
│                   ├── FSIS1502916
│                   └── N55391
└── refseq
    └── bacteria
        ├── GCF_000953495.1
        │   └── MD5SUMS
        ├── GCF_001931555.1
        │   └── MD5SUMS
        ├── GCF_001931575.1
        │   └── MD5SUMS
        ├── GCF_001931595.1
        │   └── MD5SUMS
        ├── GCF_001931615.1
        │   └── MD5SUMS
        └── GCF_002863785.1
```

I am using this in a local machine I installed StrainGE and ncbi-genome-download through conda [Version: 1.0.3]. 
Thanks for your help!

Cheers

[ERROR.txt](https://github.com/broadinstitute/StrainGE/files/6103318/ERROR.txt)

**Comment by lrvdijk** [comment]
Those errors can be ignored 👍 As long as you have some *_genomic.fna.gz files, it should be fine.

**Comment by drelo** [comment]
Thanks for your help I thought something must wrong because the first ones were empty but I left it run for half an hour and I got a lot of genomes.
