### ISSUE TITLE
Can I use my own genomes/data and skip the ncbi-download phase?

### ISSUE THREAD

**Issue by drelo** [broadinstitute/StrainGE#3]
Dear all, 

I think I understood this pipeline and I already have used similar software [PanPhlAn] that goes through a similar path (build pangenome, compare reads, etc). I now want to use StrainGE, but at the first step I would need to use my own genomes since I have newly characterized strains (which comprise a new clade) that I want to look within metagenomes recovered in this region. I already have assembled the old genomes + new genomes, I have the .fna and the .gff files for all of them new genomes. 

I did a little demo and noticed the script creates two folders, `refseq` and `human_readable.`
My question would be how to add my files in a similar fashion to this structure and rejoin the pipeline at the `python3 prepare_strainge_db.py` stage.
Thanks for your help!

Cheers

**Comment by cusoiv** [comment]
Also curious to know about this issue since I also have a group of new genomes that I'd like to work with as the reference set. @drelo were you able to figure this out later?

**Comment by drelo** [comment]
No, I couldn't progress with this.

**Comment by w1bw** [comment]
You can certainly build databases with your own genomes. Please refer to https://strainge.readthedocs.io/en/latest/create-database.html, and after you have the genome FASTAs in a directory, start with section 2 (K-merize your reference sequences). We recommend you filter out plasmid content if possible, but it's not necessary. 

If you are still having problems, or if we should improve the documentation, please let us know! We can help you get going!

**Comment by drelo** [comment]
Awesome, thanks! Thanks for the feedback. I can close the issue if you
want.

**Comment by cusoiv** [comment]
Cool! Tried with my own genomes and it worked well! Thanks!!
