### ISSUE TITLE
straingst kmerize => parallel

### ISSUE THREAD

**Issue by nick-youngblut** [broadinstitute/StrainGE#6]
A simple parallel alternative to the for loop used in the tutorial:

```
find strainge_db -name "*.fa.gz" | xargs -P 4 -I % straingst kmerize -o %.hdf5 %
```

**Comment by lrvdijk** [comment]
I often use separate cluster jobs for kmerizing samples, so I'll let people decide themselves how they want to parallelize their work. The tutorial is not meant to be an all comprehensive document on how to use bash.
