### ISSUE TITLE
straingst run => non-standard tsv

### ISSUE THREAD

**Issue by nick-youngblut** [broadinstitute/StrainGE#7]
The output for `straingst run` is not really a tsv, but rather two differently sized tsv's mashed together:

```
sample    totalkmers      distinct   pkmers  pkcov   pan%
UMB11_01  2277023860      380759656  50090   6.984   1.536
i         strain          gkmers     ikmers  skmers  cov    kcov   gcov   acct   even   spec   rapct  wscore  score
0         Esch_coli_NGF1  49631      49622   50090   0.985  7.009  6.831  0.980  0.987  1.000
```

This leads to non-standard parsing of the tables. So standard table reading approaches in python (e.g., pandas) or R (read.table) will not work. Hence the need for the"[Tips and Tricks](https://strainge.readthedocs.io/en/latest/straingst.html#tips-and-tricks)" section of the tutorial.

How about just writing 2 separate tables instead of merging the 2 into an oddly formatted txt file?

**Comment by lrvdijk** [comment]
Yeah this is a good point, and I too find it a bit of nuisance to work with these files like this. It was a bit of a case like "too many of our downstream analysis scripts already depend on this format" 😬 . 

I'll think about it, and I'll have to see if I can somehow retain some backwards compatibility.
