### ISSUE TITLE
straingr prepare-ref => .fa.gz.fa.gz does not exist!

### ISSUE THREAD

**Issue by nick-youngblut** [broadinstitute/StrainGE#8]
My `straingst run` output:

```
sample	totalkmers	distinct	pkmers	pkcov	pan%
2_T3	510807358	209690646	21113	2.130	0.880
i	strain	gkmers	ikmers	skmers	cov	kcov	gcov	acct	even	spec	rapct	old_rapctwscore	score
0	Bact_fragilis_BFG-1.fa.gz	50672	50652	21113	0.296	1.346	0.389	0.448	0.917	1.007	0.880	0.395	0.111	0.112
```

My `straingr prepare-ref` command:

```
straingr prepare-ref -s straingst_*.tsv -p "strainge_db/{ref}.fa.gz" -S similarities.tsv -o refs_concat.fasta
```

The output:

```
2022-03-16 09:15:28,748 - INFO:root:Determining which reference strains to include...
2022-03-16 09:15:28,749 - INFO:root:Reading all given StrainGST result files and collecting reported reference genomes...
2022-03-16 09:15:28,749 - INFO:root:Found 1 reference strains to include.
2022-03-16 09:15:28,749 - INFO:root:Checking file paths...
2022-03-16 09:15:28,750 - INFO:root:Path template: strainge_db/{ref}.fa.gz
2022-03-16 09:15:28,750 - ERROR:root:strainge_db/Bact_fragilis_BFG-1.fa.gz.fa.gz does not exist!
```

It appears that that neither `straingst run` nor `straingr prepare-ref ` is properly stripping off the `.fa.gz` file extensions from the strain ID. If I manually remove the `.fa.gz` extensions from the strain ID in the `straingst run` output (`Bact_fragilis_BFG-1.fa.gz` => `Bact_fragilis_BFG-1`), then `straingst run` finishes successfully.

**Comment by nick-youngblut** [comment]
I see that I can use the following instead:

```
straingr prepare-ref -s straingst_*.tsv -p "strainge_db/{ref}" -S similarities.tsv -o refs_concat.fasta
```

Still, `Bact_fragilis_BFG-1.fa.gz` is not really the strain name, as listed in the `straingst run` output, but rather the ID is `Bact_fragilis_BFG-1`

**Comment by nick-youngblut** [comment]
In regards to ` --straingst-files [STRAINGST_FILES ...]`, if the user runs StrainGE on 100's of metagenomes and supplies absolute paths for all of the `--straingst-files`, then the user could exceed the max command length set for many OSs. It would help to allow `--straingst-files` to accept one input file that lists all `STRAINGST_FILES`

**Comment by lrvdijk** [comment]
Thanks for the report! I'll investigate more deeply later but I think this is an issue with the tutorial: StrainGE uses Python's pathlib `Path.stem` as strain name, and the kmerize commands should've removed the .fa.gz component of the filename.
