### ISSUE TITLE
Use of BWA-MEM2 or BWA-MEME

### ISSUE THREAD

**Issue by nick-youngblut** [broadinstitute/StrainGE#9]
For aligning reads to the reference, can one use BWA-MEM2 or [BWA-MEME](https://github.com/kaist-ina/BWA-MEME) instead of the original BWA-MEM? The use of BWA-MEME would substantially reduce the computational cost of this step in the StrainGE pipeline (multi-fold speed-up vs BWA-MEM).

**Comment by lrvdijk** [comment]
As long as these alternative implementations also include the XA SAM tag for their alternative alignments, it should be fine.
